import Head from 'next/head'
import Link from 'next/link';

const Layout = ({ children }) => {
    return (
        <div className='w-screen h-screen bg-[#5E28BA] overflow-hidden'>
            <Head>
                <title>Cafecito DAO</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className='w-full h-20 bg-[#FFE9D2] absolute top-0 flex items-center justify-between px-20'>
                <Link href='/'>
                    <img src="/logo.svg" alt="" />
                </Link>

                <div className='flex items-center gap-4'>
                    <Link href='/forum'>
                        <a className='font-baloo font-bold text-base text-[#AA7364]' href="#">Forum</a>
                    </Link>
                    <Link href='/proposal'>
                        <a className='font-baloo font-bold text-base text-[#AA7364]' href="#">Proposal</a>
                    </Link>
                    <button className='px-4 py-2 font-baloo font-bold text-base text-[#AA7364] bg-white rounded-[16px] flex items-center gap-4'>
                        <img className='w-[20px] h-[20px]' src="/metamask.svg" alt="" />
                        Connect Wallet
                    </button>
                </div>
            </nav>
            {children}
        </div>
    );
}

export default Layout;